routes:
  - path: "/health"
    type: "GET"
    authorization: false

  - path: "/payments"
    type: "POST"
    authorization: true
    auth_type: "jwt" # Could be jwt, oauth, cloudflare_jwt
    role: "user"
    service: "control.authentication.login"
    method: "login"
    params:
      - name: "name"
        type: "string"
        required: true
      - name: "age"
        type: int
        required: false


  - path: "/payments/test-the-time/nael"
    type: "POST"
    authorization: true
    auth_type: "jwt" # Could be jwt, oauth, cloudflare_jwt
    role: "user"

  - path: "/admin"
    type: "GET"
    authorization: true
    auth_type: "cloudflare_jwt"
    role: "admin"
    service: "deriv_service_admin"
    method: "get_info"

  - path: "/account/info"
    type: "GET"
    authorization: true
    service: "deriv_service_interface_clientdb"
    method: "account_info"

  - path: "/payments/process"
    type: "POST"
    authorization: false

