routes:
  - path: "/payments"
    type: "POST"
    authorization: true
    auth_type: "jwt" # Could be jwt, oauth, cloudflare_jwt
    role: "admin"
    service: "control.authentication.login"
    method: "login"
    dec: "name_of_middleware"
    params:
      - name: "name"
        type: "string"
        required: true
      - name: "age"
        type: "integer"
        required: false
      - name: "test"
        type: "number"
        required: true
      - name: "test2"
        type: "boolean"
        required: false
  - path: "/payments2"
    type: "POST"
    authorization: true
    auth_type: "cloudflare_jwt" # Could be jwt, oauth, cloudflare_jwt
    role: "user"
    service: "control.authentication.login"
    method: "login"
    params:
      - name: "name"
        type: "string"
        required: true
      - name: "age"
        type: "number"
        required: false


  - path: "/payments/test-the-time/nael"
    type: "POST"
    authorization: true
    auth_type: "jwt" # Could be jwt, oauth, cloudflare_jwt
    role: "user"

  - path: "/admin"
    type: "GET"
    authorization: true
    auth_type: "cloudflare_jwt"
    role: "admin"
    service: "deriv_service_admin"
    method: "get_info"

  - path: "/account/info"
    type: "GET"
    authorization: true
    service: "deriv_service_interface_clientdb"
    method: "account_info"

  - path: "/payments/process"
    type: "POST"
    authorization: false

